name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  php-cs-fixer:
    name: 'PHP: CS Fixer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install

      - name: PHP-CS-Fixer
        run: composer run-script cs

  phpstan:
    name: 'PHP: PHPStan'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install

      - name: PHPStan
        run: composer run-script stan

  phpunit:
    name: 'PHP: PHPUnit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install

      - name: PHPUnit
        run: composer run-script ci-test

  typescript:
    name: 'TypeScript: ESLint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Cache npm dependencies
        uses: actions/cache@v5
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm install

      - name: Prettier
        run: npm run format:check

      - name: ESLint
        run: npm run lint
